version: '3'
services:
  jenkins-master-standby:
    ports:
      - "8081:8080"
    volumes:
      - ../../jenkins_standby/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-master-standby
    restart: always
    image: jenkinsci/blueocean
    networks:
      - backend

networks:
  backend:
    driver: bridge
